# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-10 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userask',
            name='add_time',
        ),
    ]
